name: Release

env:
  IMAGE_NAME: activemq-artemis-broker-init

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build the image
        run: podman build --tag $IMAGE_NAME:latest .

      - name: Push the image
        run: >
          export IMAGE_TAG=${GITHUB_REF#refs/tags/v} &&
          podman login quay.io --username=${{ secrets.QUAY_USERNAME }} --password-stdin <<< ${{ secrets.QUAY_PASSWORD }} &&
          podman tag $IMAGE_NAME:latest quay.io/${{ secrets.QUAY_NAMESPACE }}/$IMAGE_NAME:$IMAGE_TAG &&
          podman push quay.io/${{ secrets.QUAY_NAMESPACE }}/$IMAGE_NAME:$IMAGE_TAG &&
          podman tag $IMAGE_NAME:latest quay.io/${{ secrets.QUAY_NAMESPACE }}/$IMAGE_NAME:latest &&
          podman push quay.io/${{ secrets.QUAY_NAMESPACE }}/$IMAGE_NAME:latest
